'''
The sequence of triangle numbers is generated by adding the natural numbers.
    So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
'''

from ProjectEuler.lib import prime_factors_dict, tri_generator, prod, sieve


def solve(n=500):
    primes = sieve(10 ** 7)
    for num in tri_generator():
        prime_factors = prime_factors_dict(num, primes)
        factor_count = prod(exp + 1 for prime, exp in prime_factors.items())
        if factor_count > n:
            return num


if __name__ == '__main__':
    answer = solve()
    print(answer)
    with open('p012_ans.txt', 'w') as wb:
        wb.write(str(answer))
